### ISSUE TITLE
3. házifeladatban P104203-n feladatban a teszter hibás.

### ISSUE THREAD

**Issue by Bara03** [INBGM0212-2023/exercises#1]
<img width="306" alt="Screenshot 2023-05-05 at 20 45 36" src="https://user-images.githubusercontent.com/97089210/236542796-61741b87-c935-4edf-8e0b-cb4d4f890c81.png">

A test_call fv a kiirásban szereplő method signature -től eltérően egy int listával hívja meg az is_strictly_monotone_increasing fv-t. és True/False értéket vár returnként

Míg a test_run fv string inputot ad, és "YES"/"NO" return-t vár.

<img width="1440" alt="Screenshot 2023-05-05 at 19 20 50" src="https://user-images.githubusercontent.com/97089210/236543784-d2b8148e-8eeb-4bfe-8541-20fe1fc5ef54.png">

<img width="446" alt="Screenshot 2023-05-06 at 0 00 05" src="https://user-images.githubusercontent.com/97089210/236575694-8e687a9f-0873-442f-9c1b-f805ab8b814f.png">

<img width="952" alt="Screenshot 2023-05-05 at 23 59 08" src="https://user-images.githubusercontent.com/97089210/236575633-b4fb179b-67f6-4aa9-b932-a902c0aa8030.png">

**Comment by tothr94** [comment]
Én nem látom rossznak, egy egész listát kell átadni a függvénynek, onnan egy logikai értéket visszaadni. Az input következő sorának a beolvasása, feldarabolása és az egész lista előállítása a `main()` függvény feladata. Ugyanígy az, hogy a visszakapott értéknek megfelelően a helyes sztring kerüljön a kimenetre.

**Comment by Bara03** [comment]
Valóban, így ha a mainben dolgozol fel az inputot lefut gond nélkül.
